export const SEARCH = {
  FETCH_MULTIPLIER: 3,
  DEFAULT_LIMIT: 10,
  DEFAULT_SIMILARITY_THRESHOLD: 0.3,
  RELATED_SIMILARITY_THRESHOLD: 0.45,
  RELATED_LIMIT: 6,
  SEMANTIC_RANK_WEIGHT: 0.25,
  RATE_LIMIT_PER_MINUTE: 60,
} as const;

export const SEARCH_VALIDATION = {
  MIN_QUERY_LENGTH: 2,
  MAX_QUERY_LENGTH: 200,
  MAX_BATCH_QUERIES: 10,
  MAX_RESULTS_PER_QUERY: 50,
} as const;
