import { ConfigService } from '@nestjs/config';
import { Repository } from 'typeorm';
import { ProductDimension } from '../../../common/search/product-measurement';
import { Product } from '../../products/entities/product.entity';
import { ProductVectorRepository } from './product-vector.repository';

const EMBEDDING_MODEL = 'gemini-embedding-001';

function createRepository() {
  const queryBuilder = {
    where: jest.fn().mockReturnThis(),
    orWhere: jest.fn().mockReturnThis(),
    getMany: jest.fn().mockResolvedValue([]),
  };
  const typeOrmRepository = {
    query: jest.fn().mockResolvedValue([]),
    createQueryBuilder: jest.fn().mockReturnValue(queryBuilder),
  } as unknown as Repository<Product>;
  const configService = {
    getOrThrow: jest.fn().mockReturnValue(EMBEDDING_MODEL),
  } as unknown as ConfigService;

  return {
    repository: new ProductVectorRepository(typeOrmRepository, configService),
    query: typeOrmRepository.query as jest.Mock,
    createQueryBuilder: typeOrmRepository.createQueryBuilder as jest.Mock,
    queryBuilder,
  };
}

describe('ProductVectorRepository', () => {
  it('stores the vector together with the configured model', async () => {
    const { repository, query } = createRepository();

    await repository.updateEmbedding('product-1', '[0.1,0.2]');

    expect(query).toHaveBeenCalledWith(
      expect.stringContaining('embedding_model = $2'),
      ['[0.1,0.2]', EMBEDDING_MODEL, 'product-1'],
    );
  });

  it('only searches vectors generated by the configured model', async () => {
    const { repository, query } = createRepository();

    await repository.findBySimilarity('[0.1,0.2]', 10, 0.4, 'BO');

    expect(query.mock.calls[0][0]).toContain('p.embedding_model = $5');
    expect(query.mock.calls[0][1]).toEqual([
      '[0.1,0.2]',
      0.4,
      'BO',
      10,
      EMBEDDING_MODEL,
    ]);
  });

  it('keeps model and measurement parameters aligned', async () => {
    const { repository, query } = createRepository();

    await repository.findBySimilarity('[0.1,0.2]', 5, 0.3, 'BO', {
      dimension: ProductDimension.WIDTH,
      maxDimensionCm: 180,
    });

    expect(query.mock.calls[0][0]).toContain('~ $6');
    expect(query.mock.calls[0][0]).toContain('<= $7');
    expect(query.mock.calls[0][1]).toEqual([
      '[0.1,0.2]',
      0.3,
      'BO',
      5,
      EMBEDDING_MODEL,
      '^\\d+(\\.\\d+)?$',
      180,
    ]);
  });

  it('selects missing and outdated embeddings for regeneration', async () => {
    const { repository, createQueryBuilder, queryBuilder } = createRepository();

    await repository.findPendingEmbeddingRefresh();

    expect(createQueryBuilder).toHaveBeenCalledWith('product');
    expect(queryBuilder.where).toHaveBeenCalledWith(
      'product.embedding IS NULL',
    );
    expect(queryBuilder.orWhere).toHaveBeenCalledWith(
      'product.embedding_model IS DISTINCT FROM :embeddingModel',
      { embeddingModel: EMBEDDING_MODEL },
    );
    expect(queryBuilder.getMany).toHaveBeenCalled();
  });
});
